name: Hassan 24/7 Live Stream

on:
  workflow_dispatch:
    inputs:
      stream_key:
        description: 'YouTube Stream Key'
        required: true

jobs:
  broadcast:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg & Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          pip install yt-dlp

      - name: Start Live Stream
        run: |
          # هنا نضع سكربت البث الخاص بك (استخدم الرابط المفضل لديك)
          url=$(yt-dlp -f "best[height<=360]" -g "https://www.youtube.com/watch?v=9cauMvs6aYQ")
          
          # استمرار البث حتى لو حدث خطأ
          while true; do
            ffmpeg -re -i "$url" \
            -c:v libx264 -preset ultrafast -b:v 400k \
            -c:a aac -b:a 128k -f flv \
            "rtmp://a.rtmp.youtube.com/live2/${{ github.event.inputs.stream_key }}"
            sleep 5
          done
